### ISSUE TITLE
UTF-8 with BOM

### ISSUE THREAD

**Issue by creold** [joshbduncan/ExtendScript-Compiler#4]
This is an interesting observation. When JS files are saved as UTF-8 with BOM, the `<0xfeff>` character is added to the beginning of each imported block of code when the final script is compiled.

**Comment by joshbduncan** [comment]
Seems files saved as UTF-8 with BOM have a sequence of bytes at the start of the file ([see here](https://stackoverflow.com/a/2223926)) to declare its encoding. Can you send me a sample UTF-8 BOM file so I can determine the best way to skip those bytes during compilation? Thanks for the heads up!

**Comment by creold** [comment]
Merged.js
![image](https://github.com/user-attachments/assets/4ea99a2a-2807-45fb-8991-6497542c0513)

[test.zip](https://github.com/user-attachments/files/16465042/test.zip)

**Comment by joshbduncan** [comment]
@creold, try out the attached [utf-8-bom-fix](https://github.com/joshbduncan/escompile/tree/utf-8-bom-fix) branch and see if that works for you. I tested it on your provided example and all seems to work for me.

Just so you know, the script now checks for the 'bom' byte sequence at the beginning of any file it encounters, if it finds the sequence, it removes it and creates a temp file with the results. Finally, it uses that temp file for the compilation.

**Comment by creold** [comment]
Tried it on a script with 5 libraries. Total 6 JS files UTF-8 with BOM. It seems that the fix worked and the compiled one was without these markers. 

After that I can resave the compiled script in VSCode also in UTF-8 with BOM. As it is sometimes necessary for scripts with non-Latin interface, where there is a problem with encoding control names in ScriptUI.

**Comment by joshbduncan** [comment]
Good to know and glad it worked! I'll get this branch merged into main. Thanks as always for your help!
